### ISSUE TITLE
python dependency (`v3_9_2` to `v3_9_13` since larsoft `v09_74_00`)

### ISSUE THREAD

**Issue by jedori0228** [cafana/SRProxy#17]
`larsoft v09_74_00` now depends on `art v3_12_00` rather than `v3_09_04`, and it now depends on later version of root:
```
larsoft v09_73_00
- art v3_09_04
- root v6_22_08d
-- python v3_9_2

larsoft v09_74_00
- art v3_12_00
- root v6_26_06a
-- python v3_9_13
```
`srproxy v00.40` depends on `python v3_9_2`, so we need a new release with `python v3_9_13`

**Comment by gavinsdavies** [comment]
Please use v00.42 with the qualifier -q py3913 

I just released it early this week and was testing for another experiment. The files are on scisoft

**Comment by PetrilloAtWork** [comment]
An URL to that place (also from Gavin): [`https://scisoft.fnal.gov/scisoft/packages/srproxy/v00_42`](https://scisoft.fnal.gov/scisoft/packages/srproxy/v00_42).

**Comment by gavinsdavies** [comment]
New release of `srproxy` ([v00.42](https://scisoft.fnal.gov/scisoft/packages/srproxy/v00_42)) provided with the requisite dependency for `python v3_9_13`
